name: Build and release on Tag

on:
  push:
    tags:
      - v*.*
  workflow_dispatch:

env:
  DOCKER_IMAGE: 'lanolin25/docker-latex:v1.6'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Pull Docker to local
        run: |
          docker pull ${DOCKER_IMAGE}
      
      - name: Build PDF
        run: docker run --rm -i -v ${PWD}:/build:Z ${DOCKER_IMAGE} sh -c "make artifacts"
      
      - name: Rename artifacts
        run: |
          cd artifact
          mv report.pdf report-${{ GITHUB_REF_NAME }}.pdf
          mv report.log report-${{ GITHUB_REF_NAME }}.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifact/report-${{ GITHUB_REF_NAME }}.pdf
            artifact/report-${{ GITHUB_REF_NAME }}.log
  
  Release:
     runs-on: ubuntu-latest
     needs: Build
     if: startsWith(github.ref, 'refs/tags/')
     steps:
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: artifacts
       
       - name: Create release on tag
         uses: softprops/action-gh-release@v1
         with:
           body: |
              New release of LaTeX document
           files: |
             report-${{ GITHUB_REF_NAME }}.pdf
             report-${{ GITHUB_REF_NAME }}.log
